SubsetTypes.dfy(7,18): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(8,9): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(10,23): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(11,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(15,15): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(16,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(19,11): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(21,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(23,8): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(30,4): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(31,7): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(42,24): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(44,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(49,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(54,4): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(62,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(66,20): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(67,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(91,32): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
SubsetTypes.dfy(93,20): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then

Dafny program verifier finished with 17 verified, 20 errors
